agentsapp/urls.py
from django.urls import path
from .views import *

app_name = 'agentsapp'

urlpatterns = [
    path('', AgentListView.as_view(), name='agents'),
    path('create_agent/', AgentCreateView.as_view(), name='create_agent'),

]

customersapp/urls.py
from django.urls import path
from .views import *

app_name = "customersapp"
urlpatterns = [
    #susyscrmprojectga yuboradigan url so'rovlarini shu yerda kutib olamiz: 127.0.0.1:8000/all/
    path('', CustomersListView.as_view(), name='customers_list'),
    #susyscrmproject/urls.py dan kelgan 127.0.0.1:8000/customers/id so'rovlarga <pk> qo'shib, customers_details metodga yuboradi.
    path('<int:pk>/', CustomerDetailView.as_view(), name = 'customer_details'),
    #127.0.0.1:8000/customers/create
    path('create/', CustomerCreateView.as_view(), name = 'create_customer' ),
    path('categories/', CategoryListView.as_view(), name = 'categories' ),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name = 'category_detail'),
    path('<int:pk>/update/', CustomerUpdateView.as_view(), name='update_customer'),
    path('<int:pk>/determine_agent/', AgentAssignView.as_view(), name='assign_agent'),
    path('<int:pk>/category_update_detail/', CustomerCategoryUpdateView.as_view(), name='category_update_detail'),
    path('<int:pk>/delete/', CustomerDeleteView.as_view(), name='delete_customer')
    

]

susyscrmproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from customersapp.views import HomeView, SignUpView

urlpatterns = [
    #customersapp dan keladigan url so'rovlarini shu yerda kutib olamiz: 127.0.0.1:8000/admin/
    path('admin/', admin.site.urls),

    #path ichidagi 'customers/' direktoriyasi customers_list.html ichidagi href="/customers/" dan kelgan so'rovlarni qabul qilib,
    #customersapp/urls.py ga uzatadi.
    path('customers/', include('customersapp.urls', namespace='customersapp')),
    path('agents/', include('agentsapp.urls', namespace='agentsapp')),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('password_reset/', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

customersapp/models.py
from unicodedata import category
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_company = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user.username)

class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=1)
    company = models.ForeignKey(UserProfile, null=True, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name='customer_related_name', null=True, blank=True, on_delete=models.SET_NULL)


    def __str__(self):
        return (self.first_name+' '+self.last_name)

class Category(models.Model):
    name = models.CharField(max_length=20)
    company = models.ForeignKey(UserProfile, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    company = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


def post_user_create(sender, instance, created, **kwargs):
    #print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_create, sender=User)

customersapp/forms.py
from dataclasses import fields
from urllib import request
from django import forms
from .models import Agent, Customer, User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent'
        )

class CustomerCreateForm(forms.Form):
    first_name = forms.CharField(max_length=20,)
    last_name = forms.CharField(max_length=30)
    age = forms.IntegerField(min_value=16)
    agent = forms.CharField(max_length=50)

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agents = Agent.objects.filter(company=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset=agents

class CustomerCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            'category',
        )

customersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse 
from django.http import HttpResponse
from django.views.generic import *
from .models import *
from .forms import *
from agentsapp.mixins import CompanyAndLoginRequiredMixin

# Create your views here.

class SignUpView(CreateView):
    template_name = "registration/signup.html"
    form_class = NewUserForm

    def get_success_url(self):
        return reverse('customersapp:customers_list')

class HomeView(TemplateView):
    template_name = 'home.html'

class CustomersListView(LoginRequiredMixin, ListView):
    template_name = 'customers/customers_list.html'
    context_object_name = 'customers'

    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Customer.objects.all()
        else:
            queryset = Customer.objects.filter(company = user.agent.company)
            queryset = queryset.filter(agent_user = self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CustomersListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_company:
            queryset = Customer.objects.filter(
                company = user.userprofile,
                agent__isnull = True
            )
            context.update({
                "unassigned_customers":queryset
            })
        return context

class CustomerDetailView(CompanyAndLoginRequiredMixin, DetailView):
    template_name = 'customers/details.html'
    queryset = Customer.objects.all()
    context_object_name = 'customer'

class CustomerCreateView(CompanyAndLoginRequiredMixin, CreateView):
    template_name = 'customers/create_customer.html'
    form_class = CustomerModelForm

    def get_success_url(self):
        return reverse('customersapp:customers_list')

    def form_valid(self, form):
        customer = form.save(commit=False)
        customer.company = self.request.user.userprofile
        customer.save()
        send_mail(
            subject = 'Bu mijoz yaratilgan',
            message = "Yangi mijoz qo'shing",
            from_email = "test@test.com",
            recipient_list = ["test2@test.com"],
        )

class CustomerUpdateView(CompanyAndLoginRequiredMixin, UpdateView):
    template_name = 'customers/update_customer.html'
    form_class = CustomerModelForm
    queryset = Customer.objects.all()
    context_object_name = 'customer'

    def get_success_url(self):
        return reverse('customersapp:customers_list')

class CustomerDeleteView(CompanyAndLoginRequiredMixin, DeleteView):
    template_name = 'customers/delete.html'
    form_class = CustomerModelForm
    queryset = Customer.objects.all()

    def get_success_url(self):
        return reverse('customersapp:customers_list')

class AgentAssignView(CompanyAndLoginRequiredMixin, FormView):
    template_name = 'customers/determine_agent.html'
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AgentAssignView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            'request':self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse('customersapp:customers_list')

    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        customer = Customer.objects.get(id = self.kwargs['pk'])
        customer.agent = agent
        customer.save()
        return super(AgentAssignView, self).form_valid(form)

class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "customers/category.html"
    context_object_name = 'categories'
    #queryset = models.Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_company:
            queryset = Customer.objects.filter(
                company = user.userprofile,
            )
        else:
            queryset = Category.objects.filter(
                company = user.agent.company
            )
        context.update({
                "unassigned_category_quantity":queryset.filter(category__isnull=True).count()
            })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Category.objects.filter(
                company = user.userprofile
                )
        else:
            queryset = Category.objects.filter(
                company = user.agent.company
                )
        return queryset

class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = 'customers/category_details.html'
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Category.objects.filter(
                company = user.userprofile
                )
        else:
            queryset = Category.objects.filter(
                company = user.agent.company
                )
        return queryset

class CustomerCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'customers/category_update_detail.html'
    form_class = CustomerCategoryUpdateForm
    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Customer.objects.filter(
                company = user.userprofile
            )
        else:
            queryset = Customer.objects.filter(
                company = user.agent.company
            )
        return queryset

    def get_success_url(self):
        return reverse('customersapp:customers_list')

customersapp/templates/customers/category.html
{% extends "base.html" %}

{% block title %} Toifalar {% endblock %}

{% block content %}
    <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Fanlar</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Fanga yozilgan o'quvchilar</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
            <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Fanlar</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Soni</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="px-4 py-3">Aniqlanmagan</td>
                    <td class="px-4 py-3">{{ unassigned_category_customers }}</td>

            {% for cat in categories %}
            <tr>
                <td class="px-4 py-3"> 
                    <a class="hover:text-blue-500" href=" {% url 'customersapp:category_detail' cat.pk %} "> {{ cat.name }}
                    </a>
                </td>
                <td class="px-4 py-3">5 Mb/s</td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
        </div>
        <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
        <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Batafsil
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
        <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
        </div>
    </div>
    </section>

{% endblock %}

customersapp/templates/customers/category_details.html
{% extends "base.html" %}

{% block title %} Toifalar {% endblock %}

{% block content %}
    <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{category.name}}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Banh mi cmoon twee</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
            <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"> 222</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Speed</th>
            </tr>
            </thead>
            <tbody>
              
             <tr>
                <td class="px-4 py-3">Biriktirilmagan fanlar soni</td>
                <td class="px-4 py-3">soni</td>
            </tr>


            {% for cat in category.customer_related_name.all %}
            <!-- bu yerdagi ya'ni, category.customers.all dagi, customers models.py faylidagi Customer modilining category 
            qatoridagi "related_name=customers" ning customers bilan bir xil bo'lishi zarur va shart --> 
            <tr>
                <td class="px-4 py-3"><a href="{% url 'customersapp:customer_details' cat.pk %}"> {{ cat.first_name }} </a></td>
                <td class="px-4 py-3">5 Mb/s</td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
        </div>
    </div>
    </section>

{% endblock %}

customersapp/templates/customers/category_update_detail.html
{% extends 'base.html' %}

{% block title %} Mijoz toifasini tahrirlash {% endblock title %}

{% block content %}

    <h3> Mijoz Fani </h3>
    <br>
    
    <form method="post">
        <!-- 
        Ismni kiriting:         <input type="text">
        Familiyasini kiriting:  <input type="text">
        Yoshini kiriting:       <input type="integer">
        -->
        <p>
        {% csrf_token %}
        <br>

        {{ form.as_p }}

        <button type="submit"> Saqlash </button>
    </form>
{% endblock %}

customersapp/templates/customers/create_customer.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %} Yangi mijoz qo'shish {% endblock title %}

{% block content %}

    <a href="/customers"> Barcha mijozlar sahifasiga o'tish</a>
    <br>

    <h3>Yangi mijozni qo'shish</h3>
    <form method="post">
        <!-- 
        Ismni kiriting:         <input type="text">
        Familiyasini kiriting:  <input type="text">
        Yoshini kiriting:       <input type="integer">
        -->
        <p>
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit"> Saqlash </button>
    </form>
{% endblock %}

customersapp/templates/customers/customers_list.html
{% extends 'base.html' %}

{% block title %} Mijozlar ro'yxati{% endblock title%}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                </h3 class="text-4xl text-gray-800">Mijozlar</h3>
                <a href="{% url 'customersapp:categories' %}">Toifalar</a>
            </div>
            {% if request.user.is_company %}
            <div>
                <a class="y=text-gray-500 hover:text-blue-700" href="{% url 'customersapp:create_customer'%}"> 
                Yangi mijoz qo'shish
                </a>
            </div>
            {% endif %}
        </div>
        <div class="flex flex-wrap">
            {% for customer in customers %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                        {{ customer.first_name }} {{ customer.last_name }}
                        </h2>
                        <p class="leading-relaxed text-base">
                        SUSYS Academy o'quvchisi
                        </p>
                        <a href="{% url 'customersapp:customer_details' customer.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                        Batafsil
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if unassigned_customers.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h3 class="text-4xl text-gray-800">Agent noma'lum mijozlar</h3>
                </div>
                {% for customer in unassigned_customers %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ customer.first_name }} {{ customer.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
                            </p>
                            <a href="{% url 'customersapp:assign_agent' customer.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Agentni biriktirish
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7">
                                    </path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>

{% endblock content %}

customersapp/templates/customers/delete.html
{% extends 'base.html' %}

{% block title %} Mijozni o'chirish {% endblock title %}

{% block content %}

    <a href="/customers"> Barcha mijozlar sahifasiga o'tish</a>
    <br>

    <h3>Mijozni o'chirish</h3>
    <form method="post">
        <!-- 
        Ismni kiriting:         <input type="text">
        Familiyasini kiriting:  <input type="text">
        Yoshini kiriting:       <input type="integer">
        -->
        <p>
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit"> O'chirish </button>
    </form>
{% endblock %}

customersapp/templates/customers/details.html
{% extends 'base.html' %}

{% block title %} {{customer.last_name}} {{ customer.first_name }}ning ma'lumotlari{% endblock title%}

{% block content%}

    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    
                    <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">Mijozlar</h2>
                            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{customer.first_name}} {{customer.last_name}}ning ma'lumotlari
                            </h1>
                                <div class="flex mb-4">
                                    <a href="{% url 'customersapp:customers_list'%}"  class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                                        Barcha mijozlar sahifasiga o'tish
                                    </a>
                                    
                                    <a href="{% url 'customersapp:category_update_detail' customer.pk %}">
                                    Fani
                                        </a>
                                    <a href="{% url 'customersapp:update_customer' customer.pk %}">
                                        Mijoz ma'lumotlarini tahrirlash
                                    </a>
                                </div>
                                <p class="leading-relaxed mb-4">Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
                                </p>
                                <div class="flex border-t border-gray-200 py-2">
                                    <span class="text-gray-500">Yoshi</span>
                                    <span class="ml-auto text-gray-900">{{ customer.age }}</span>
                                </div>
                                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                                    <span class="text-gray-500">Telefon raqami</span>
                                    <span class="ml-auto text-gray-900">+998990591714</span>
                                </div>
                                <div class="flex">
                                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button
                                    </button>
                                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                            <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                                        </svg>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <h2>SUSYS Customer details</h2><br><br>
    <h4>Ismi: {{ customer.first_name }}</h4>
    <h4>Familiyasi: {{ customer.last_name }}</h4>
    <a href="{% url 'customersapp:delete_customer' customer.pk %}"> Mijozni o'chirish</a>

{% endblock %}

customersapp/templates/customers/determine_agent.html
{% extends 'base.html' %}

{% block title %} Agentni aniqlash {% endblock title %}

{% block content %}

    <a href="/customers"> Barcha mijozlar sahifasiga o'tish</a>
    <br>

    <h3>Agentni tanlang</h3>
    <form method="post">
        <!-- 
        Ismni kiriting:         <input type="text">
        Familiyasini kiriting:  <input type="text">
        Yoshini kiriting:       <input type="integer">
        -->
        <p>
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <hr>

        <button type="submit"> Saqlash </button>
    </form>
{% endblock %}

customersapp/templates/customers/update_customer.html
{% extends 'base.html' %}

{% block title %} Tahrirlash {% endblock title %}

{% block content%}

 <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Mijozning ismi</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{customer.first_name}} {{customer.last_name}}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'customersapp:customers_list'%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"> 
                        Barcha mijozlar sahifasiga o'tish
                    </a>        
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Reviews
                    </a>   
                    <a href = "{{customer.first_name}} {{customer.last_name}}"class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"> Ma'lumotlarini o'zgartirish
                    </a>
                </div>
                    <form method="post">
                        <!-- 
                        Ismni kiriting:         <input type="text">
                        Familiyasini kiriting:  <input type="text">
                        Yoshini kiriting:       <input type="integer">
                        -->
                        <p>
                        {% csrf_token %}

                        {{ form.as_p }}

                        <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Saqlash</button>
                        <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">            
                        <a href="{% url 'customersapp:delete_customer' customer.pk %}"> Mijozni o'chirish</a>
                        </button>
                    </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}