agentsapp/urls.py
from django.urls import path
from .views import *

app_name = 'agentsapp'

urlpatterns = [
    path('', AgentListView.as_view(), name='agents'),
    path('create_agent/', AgentCreateView.as_view(), name='create_agent'),

]

susyscrmproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from customersapp.views import HomeView, SignUpView

urlpatterns = [
    #customersapp dan keladigan url so'rovlarini shu yerda kutib olamiz: 127.0.0.1:8000/admin/
    path('admin/', admin.site.urls),

    #path ichidagi 'customers/' direktoriyasi customers_list.html ichidagi href="/customers/" dan kelgan so'rovlarni qabul qilib,
    #customersapp/urls.py ga uzatadi.
    path('customers/', include('customersapp.urls', namespace='customersapp')),
    path('agents/', include('agentsapp.urls', namespace='agentsapp')),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('password_reset/', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

agentsapp/models.py
from django.db import models

# Create your models here.

agentsapp/forms.py
import imp
from django import forms 
#from customersapp.models import Agent
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from customersapp.models import User

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

agentsapp/views.py
from email import message
from re import template
from django.shortcuts import render
from django.views import generic
from .mixins import CompanyAndLoginRequiredMixin
from customersapp.models import Agent
from .forms import AgentModelForm
from django.urls import reverse
import random
from django.core.mail import send_mail
# Create your views here.

class AgentListView(CompanyAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agents_list.html'

    def get_queryset(self):
        #filterlash
        company = self.request.user.userprofile
        return Agent.objects.filter(company=company)


class AgentCreateView(CompanyAndLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/create_agent.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agentsapp:agents')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_company = False
        user.is_agent = True
        user.set_password(f"{random.randint(0,1000)}")
        #agent.profile = self.request.user.userprofile
        user.save()
        Agent.objects.create(
            user = user,
            company = self.request.user.userprofile
        )
        send_mail(
            subject = "Bu Agent yaratilgan",
            message = "Yangi Agent yaratilgan",
            from_email = "jimamaliyev@gmail.com",
            recipient_list=[user.email],
        )
        return super(AgentCreateView, self).form_valid(form)


#sucrm-52 nomli arxivdan chiqarilib olindi.
class AgentDetailView(CompanyAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_details.html"
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.filter(company=company)

class AgentUpdateView(CompanyAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/update_agent.html"
    form_class = AgentModelForm

    def get_queryset(self):
        return Agent.objects.all()

    def get_success_url(self):
        return reverse("agentsapp:agents")

class AgentDeleteView(CompanyAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/delete_agent.html"
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.filter(company=company)

    def get_success_url(self):
        return reverse("agentsapp:agents")

agentsapp/templates/agents/agent_details.html
{% extends 'base.html' %}

{% block title %}Agent ma'lumotlari {% endblock %}

{% block content %}

    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agentlar</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
        <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Ma'lumotlar
            </a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              O'zgartirish
            </a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Telefon raqami</span>
          <span class="ml-auto text-gray-900">+998990591714</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
    
    </div>
    </div>
    </section>
    
{% endblock %}

agentsapp/templates/agents/agents_list.html
{% extends 'base.html' %}

{% block title %} Agentlar{% endblock title%}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Agentlar</h1>
            </div>
            <div>
                <h2>SUSYS Customers</h2>
                <a class="y=text-gray-500 hover:text-blue-700" href="{% url 'agentsapp:create_agent' %}"> Yangi agent qo'shish</a>
            </div>
        </div>
        <div class="flex flex-wrap">
            {% for obj in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ obj.user.username }}</h2>
                        <p class="leading-relaxed text-base">SUSYS Academy o'quvchisi</p>
                        <a href="" class="mt-3 text-indigo-500 inline-flex items-center">Batafsil
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7">
                                </path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div
</section>

{% endblock %}

agentsapp/templates/agents/create_agent.html
{% extends 'base.html' %}

{% block title %} Yangi mijoz qo'shish {% endblock title %}

{% block content %}

    <a href="/customers"> Barcha mijozlar sahifasiga o'tish</a>
    <br>

    <h3>Yangi agentni qo'shish</h3>
    <form method="post">
        <!-- 
        Ismni kiriting:         <input type="text">
        Familiyasini kiriting:  <input type="text">
        Yoshini kiriting:       <input type="integer">
        -->
        <p>
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit"> Saqlash </button>
    </form>
{% endblock %}

agentsapp/templates/agents/delete_agent.html
{% extends 'base.html' %}

{% block title %} Agent o'chirish {% endblock %}

{% block content %}

    <a href="/agents/">Agentlar bo'limi</a>
    <h1>O'chirishga aminmisiz</h1>
    <form method="post">
        <p>
        {% csrf_token %} 
        {{ forms.as_p }}
        <button type="submit">Jo'natish</button>
    </form>

{% endblock %}